apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-controller-manager-images
  namespace: openshift-cloud-controller-manager-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
data:
  images.json: >
    {
      "cloudControllerManagerOperator": "quay.io/openshift/origin-cluster-cloud-controller-manager-operator",
      "cloudControllerManagerAWS": "quay.io/openshift/origin-aws-cloud-controller-manager",
      "cloudControllerManagerAzure": "quay.io/openshift/origin-azure-cloud-controller-manager",
      "cloudNodeManagerAzure": "quay.io/openshift/origin-azure-cloud-node-manager",
      "cloudControllerManagerGCP": "quay.io/openshift/origin-gcp-cloud-controller-manager",
      "cloudControllerManagerIBM": "quay.io/openshift/origin-ibm-cloud-controller-manager",
      "cloudControllerManagerOpenStack": "quay.io/openshift/origin-openstack-cloud-controller-manager",
      "cloudControllerManagerVSphere": "quay.io/openshift/origin-vsphere-cloud-controller-manager"
    }
